### ISSUE TITLE
Script rotto

### ISSUE THREAD

**Issue by dennisangemi** [vi-enne/profughiUcraina#10]
Ciao @vi-enne , mi sono appena reso conto del fatto che lo script si è rotto. Appena abbiamo un po' di tempo diamo un'occhiata

**Comment by vi-enne** [comment]
@dennisangemi grazie della segnalazione.
Il pacchetto `rtweet` è stato aggiornato e riscritto.
Un quick fix che ho usato in un'altra repo è di forzare la vecchia versione del pacchetto.

**Comment by vi-enne** [comment]
Risolto.

**Comment by dennisangemi** [comment]
Grazie <3
