### ISSUE TITLE
Traduzione inglese?

### ISSUE THREAD

**Issue by dennisangemi** [vi-enne/profughiUcraina#2]
Ciao @vi-enne , secondo te ha senso scrivere il repo in inglese? Mi riferisco al readme, ai metadati, alle colonne del csv...

**Comment by vi-enne** [comment]
Forse nelle due lingue?
A questo punto avrebbe senso anche fare un output in inglese per quanto riguarda i nomi delle colonne?

**Comment by dennisangemi** [comment]
Il [README.md](https://github.com/vi-enne/profughiUcraina#readme) e i medati [datapackage.yaml](https://github.com/vi-enne/profughiUcraina/blob/main/datapackage.yaml) li ho scritti in inglese ma ti pregherei di fare un check

**Comment by dennisangemi** [comment]
Appena posso preparo anche una traduzione del readme in italiano

**Comment by dennisangemi** [comment]
@vi-enne chiudiamo questa issue solo dopo la tua benedizione.

- Il readme ha una [versione inglese](https://github.com/vi-enne/profughiUcraina#readme) e una [versione italiana](https://github.com/vi-enne/profughiUcraina#versione-italiana)
- I metadati [datapackage.yaml](https://github.com/vi-enne/profughiUcraina/blob/main/datapackage.yaml) descrivono il file csv `data/outputProfughi.csv` in inglese (ma gli header delle colonne sono comunque in italiano. Non penso sia un problema ma per coerenza tradurrei anche gli header. Che ne pensi?)

**Comment by vi-enne** [comment]
Ok! Grazie :)
