### ISSUE TITLE
tweet.csv encoding

### ISSUE THREAD

**Issue by dennisangemi** [vi-enne/profughiUcraina#3]
Abbiamo qualche problema con l'enconding del file tweet.csv. Il report di validazione di frictionless ci restituisce questo risultato:

```
# -----
# valid: data/outputProfughi.csv
# -----
# -------
# invalid: data/tweet.csv
# -------

===  =====  ==============  ==================================================================================================================================
row  field  code            message                                                                                                                           
===  =====  ==============  ==================================================================================================================================
            encoding-error  The data source could not be successfully decoded: 'utf-8' codec can't decode byte 0xe8 in position 268: invalid continuation byte
===  =====  ==============  ==================================================================================================================================
```

**Comment by dennisangemi** [comment]
Testo del tweet di esempio:

[#AccoglienzaUcraina](https://twitter.com/hashtag/AccoglienzaUcraina?src=hashtag_click) Sono 78.021 le persone giunte finora in Italia: 40.204 donne, 7.659 uomini e 30.158 minori. Rispetto a ieri, l'incremento è di 1.174 ingressi nel territorio nazionale: le destinazioni principali sono [#Milano](https://twitter.com/hashtag/Milano?src=hashtag_click), [#Roma](https://twitter.com/hashtag/Roma?src=hashtag_click), [#Napoli](https://twitter.com/hashtag/Napoli?src=hashtag_click) e [#Bologna](https://twitter.com/hashtag/Bologna?src=hashtag_click).

raw csv

```
#31marzo https://t.co/iUsRiYz50A"
"2585782921","1509099892815405057","2022-03-30 09:27:06","Viminale","#AccoglienzaUcraina Sono 76.847  le persone giunte finora in Italia: 39.617 donne, 7.435 uomini e 29.795 minori.
Rispetto a ieri, l'incremento � di 1.732 ingressi nel territorio nazionale: le destinazioni principali sono #Milano, #Roma, #Napoli e #Bologna.
```

il problema pare essere la "è"

**Comment by dennisangemi** [comment]
Possibili soluzioni:

**Comment by vi-enne** [comment]
Per adesso ho rimosso il file, alla fine non è essenziale.

**Comment by dennisangemi** [comment]
Chiudiamo. Riapriamo se dovessero esserci altri problemi
