### ISSUE TITLE
rinominare outputProfughi.csv?

### ISSUE THREAD

**Issue by dennisangemi** [vi-enne/profughiUcraina#6]
cambiamo nome del file? `refugees.csv`? Che ne dici?

**Comment by vi-enne** [comment]
Lascerei un nome in italiano, visto anche che i nomi delle colonne sono in italiano.
Forse potremmo creare due file nelle due lingue?

**Comment by dennisangemi** [comment]
[Questo commento](https://github.com/vi-enne/profughiUcraina/issues/7#issuecomment-1086930202) è stato illuminante ergo secondo me va benissimo un solo file con nomi colonne in italiano ma documentati in inglese.
