### ISSUE TITLE
rename repo?

### ISSUE THREAD

**Issue by dennisangemi** [vi-enne/profughiUcraina#7]
Cambiare il nome del repo è sempre rischiosissimo ma credo che siamo in tempo dato che non è stato ancora lanciato questo mini progetto. Utilizzerei un nome inglese ma non so esattamente quale. Parliamone ;) Cosa ne pensi?

- UkrainianRefugeesItaly

**Comment by vi-enne** [comment]
Essendo dati italiani penso sia meglio lasciarla in italiano, anche per limitare gli anglicismi.
Il README nelle due lingue credo sia sufficiente.

Che ne pensi?

**Comment by dennisangemi** [comment]
> Che ne pensi?

Mi hai convinto. Chiudo ;) grazie
