### ISSUE TITLE
add description and tag

### ISSUE THREAD

**Issue by dennisangemi** [vi-enne/profughiUcraina#8]
Ciao @vi-enne , appena puoi, inseriresti una descrizione e alcuni tag al repo? Grazie ;)
![image](https://user-images.githubusercontent.com/77018886/161427427-dcb79f10-5321-4ccc-b570-758bcb566295.png)

**Comment by vi-enne** [comment]
![image](https://user-images.githubusercontent.com/44818674/161444318-51607946-82c1-40ca-a335-37f16d4c0f06.png)

Fatto. Posso aggiungerne altre se hai suggerimenti, altrimenti puoi chiudere.

**Comment by dennisangemi** [comment]
A quei tag aggiungerei `data` e `csv`. Che ne pensi?

**Comment by vi-enne** [comment]
Fatto. Chiudo.

**Comment by dennisangemi** [comment]
Grazie @vi-enne
